import json, base64, subprocess, time, sys, os
from playwright.sync_api import sync_playwright
ROOT = '/home/claude/pereplet'; OUT = ROOT + '/test/shots'; os.makedirs(OUT, exist_ok=True)
JSZIP = '/home/claude/.npm-global/lib/node_modules/docx/node_modules/jszip/dist/jszip.min.js'
guide = open(ROOT + '/seed/guide.json').read()
meta = {"title": "Путеводитель по AynoBook", "author": "Библиотека AynoBook", "genre": "Справка", "description": "Короткая книжка о том, как листать, закладывать страницы, выделять цитаты и настраивать страницу под себя.", "lang": "ru", "format": "html", "chars": 5613, "words": 900, "chapters": [{"t": "Вместо предисловия", "l": 1, "n": 929}, {"t": "Как листать", "l": 1, "n": 1157}, {"t": "Ленточка-закладка", "l": 1, "n": 747}, {"t": "Маркер и заметки на полях", "l": 1, "n": 850}, {"t": "Как настроить страницу", "l": 1, "n": 895}, {"t": "Для библиотекаря", "l": 1, "n": 1035}], "cover": None, "coverData": None, "hidden": False, "addedAt": "2026-09-20T10:00:00.000Z", "updatedAt": 1}
mock = open(ROOT + '/test/mock.js').read().replace('__GUIDE__', json.dumps(guide)).replace('__META__', json.dumps(meta))
page_html = open(ROOT + '/dist/aynobook.html').read()
skel = '<!doctype html><html><head><meta charset=utf8><meta name=viewport content="width=device-width,initial-scale=1,viewport-fit=cover"><style>:root{color-scheme:light;padding-top:env(safe-area-inset-top,0px);padding-bottom:env(safe-area-inset-bottom,0px)}body{margin:0;font:14px system-ui;background:#fafafa}img{max-width:100%}[hidden]{display:none!important}</style></head><body>' + page_html + '</body></html>'
open(ROOT + '/test/index.html', 'w').write(skel)
srv = subprocess.Popen(['python3', '-m', 'http.server', '8765', '--bind', '127.0.0.1'], cwd=ROOT, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
time.sleep(1)
logs = []
def step(msg): print('>>', msg, flush=True)
try:
  with sync_playwright() as p:
    br = p.chromium.launch()
    pg = br.new_page(viewport={'width': 1360, 'height': 860})
    pg.on('console', lambda m: logs.append(f'{m.type}: {m.text}') if m.type in ('error', 'warning') else None)
    pg.on('pageerror', lambda e: logs.append('PAGEERROR: ' + str(e)))
    pg.route('https://cdnjs.cloudflare.com/ajax/libs/jszip/**', lambda r: r.fulfill(path=JSZIP, content_type='application/javascript'))
    pg.route(lambda u: 'fonts.g' in u, lambda r: r.abort())
    def blob(route):
      bid = route.request.url.split('/_blob/')[1]
      res = pg.evaluate('id => window.__blobB64(id)', bid)
      if not res: return route.fulfill(status=404, body='')
      route.fulfill(status=200, body=base64.b64decode(res['b64']), content_type=res['type'])
    pg.route('**/_blob/**', blob)
    pg.add_init_script(mock)
    pg.goto('http://127.0.0.1:8765/test/index.html')
    pg.wait_for_selector('#regForm', timeout=8000)
    time.sleep(0.8); pg.screenshot(path=OUT + '/01_gate.png')
    pg.click('#regGo'); pg.wait_for_selector('#app:not([hidden])', timeout=8000); time.sleep(1.2)
    step('in app, view=' + pg.evaluate("document.querySelector('[aria-current=page]')?.dataset.go"))
    pg.screenshot(path=OUT + '/02_library.png')
    pg.click('.tabs [data-go=admin]'); time.sleep(0.4)
    files = [ROOT + '/test/' + f for f in ['Тестовая повесть.epub', 'Примеров - Дорога домой.fb2', 'Иванов - Записки наблюдателя.txt']]
    pg.set_input_files('#fileIn', files)
    for _ in range(60):
      n = pg.evaluate("document.querySelectorAll('[data-act=publish]').length + document.querySelectorAll('.qerr').length")
      if n >= 3: break
      time.sleep(0.5)
    step('queue: ' + json.dumps(pg.evaluate("[...document.querySelectorAll('.qitem')].map(q=>q.innerText.replace(/\\s+/g,' ').slice(0,220))"), ensure_ascii=False))
    pg.screenshot(path=OUT + '/03_admin.png', full_page=True)
    pg.evaluate("document.querySelectorAll('[data-act=publish]').forEach(b=>b.click())")
    for _ in range(40):
      if pg.evaluate("document.querySelectorAll('.qitem .badge').length") >= 3: break
      time.sleep(0.4)
    step('published; books=' + str(pg.evaluate("window.__mock.store.size")))
    time.sleep(0.6); pg.screenshot(path=OUT + '/03b_admin_done.png', full_page=True)
    pg.click('.tabs [data-go=library]'); time.sleep(1.2)
    pg.screenshot(path=OUT + '/04_shelf.png', full_page=True)
    pg.click('.tile:has-text("Туман над рекой")'); time.sleep(0.8)
    pg.screenshot(path=OUT + '/05_sheet.png')
    pg.click('#bsRead')
    pg.wait_for_function("document.querySelector('#rdFolio').textContent.length>0", timeout=10000); time.sleep(1.4)
    pg.screenshot(path=OUT + '/06_reader.png')
    step('folio ' + pg.inner_text('#rdFolio') + ' | ' + pg.inner_text('#rdLeft') + ' | ' + pg.inner_text('#rdRight'))
    for i in range(3): pg.keyboard.press('ArrowRight'); time.sleep(0.6)
    step('after 3 next: ' + pg.inner_text('#rdFolio') + ' | chap ' + pg.inner_text('#rdChap'))
    pg.keyboard.press('b'); time.sleep(0.7)
    step('ribbon on: ' + str(pg.evaluate("document.querySelector('#rdRibbon').classList.contains('on')")))
    pg.evaluate("""() => { const vp=document.querySelector('#rdViewport').getBoundingClientRect(); const bl=[...document.querySelectorAll('#rdFlow .blk')].find(b=>{const r=b.getClientRects()[0]; return r && r.left>=vp.left && r.left<vp.right-50 && b.textContent.length>80}); const w=document.createTreeWalker(bl,NodeFilter.SHOW_TEXT); const n=w.nextNode(); const r=document.createRange(); r.setStart(n,5); r.setEnd(n,45); const s=getSelection(); s.removeAllRanges(); s.addRange(r); }""")
    time.sleep(0.7)
    step('pop on: ' + str(pg.evaluate("document.querySelector('#rdPop').classList.contains('on')")))
    pg.screenshot(path=OUT + '/07_select.png')
    pg.click('#rdPop .dot[data-hlc=g]'); time.sleep(0.4)
    step('marks: ' + str(pg.evaluate("document.querySelectorAll('#rdFlow mark.hl').length")))
    pg.keyboard.press('t'); time.sleep(0.6); pg.click('[data-ptab=marks]'); time.sleep(0.3)
    pg.screenshot(path=OUT + '/08_panel.png')
    pg.keyboard.press('Escape'); time.sleep(0.4)
    pg.mouse.move(680, 20); time.sleep(0.5); pg.click('#rdSetBtn'); time.sleep(0.5); pg.screenshot(path=OUT + '/09_settings.png')
    pg.click('[data-set=theme][data-v=night]'); time.sleep(0.3)
    pg.click('[data-set=mode][data-v=scroll]'); time.sleep(0.8)
    pg.keyboard.press('Escape'); time.sleep(0.3)
    pg.screenshot(path=OUT + '/10_scroll_night.png')
    step('scroll folio ' + pg.inner_text('#rdFolio') + ' ' + pg.inner_text('#rdRight'))
    pg.mouse.move(680, 20); time.sleep(0.4); pg.click('#rdSetBtn'); time.sleep(0.3); pg.click('[data-set=mode][data-v=paged]'); pg.click('[data-set=theme][data-v=paper]'); time.sleep(0.4); pg.keyboard.press('Escape'); time.sleep(0.2)
    pg.keyboard.press('Escape'); time.sleep(0.8)
    pg.click('.tile:has-text("Дорога домой")'); time.sleep(0.6); pg.click('#bsRead')
    pg.wait_for_function("document.querySelector('#rdFolio').textContent.length>0", timeout=10000); time.sleep(1.3)
    pg.keyboard.press('ArrowRight'); time.sleep(0.8)
    pg.screenshot(path=OUT + '/11_fb2.png')
    step('fb2 chap: ' + pg.inner_text('#rdChap') + ' folio ' + pg.inner_text('#rdFolio'))
    pg.keyboard.press('Escape'); time.sleep(0.6)
    step('store user docs: ' + json.dumps([k for k in pg.evaluate("[...window.__mock.store.keys()]") if k.startswith('data/')], ensure_ascii=False))
    pg.set_viewport_size({'width': 390, 'height': 844}); time.sleep(0.8)
    pg.screenshot(path=OUT + '/12_mobile_lib.png', full_page=True)
    pg.click('.tile:has-text("Путеводитель")'); time.sleep(0.6); pg.click('#bsRead')
    pg.wait_for_function("document.querySelector('#rdFolio').textContent.length>0", timeout=10000); time.sleep(1.3)
    pg.screenshot(path=OUT + '/13_mobile_reader.png')
    step('overflow x: ' + str(pg.evaluate("document.documentElement.scrollWidth")))
    br.close()
finally:
  srv.terminate()
print('\n'.join(logs[:40]) or 'no console errors')
